### ISSUE TITLE
Web typography spacing out of date

### ISSUE THREAD

**Issue by mebates** [cfpb/design-manual#269]
The ["Web typesetting"](http://cfpb.github.io/design-manual/identity/typography.html#typesetting-for-readability) portion of the Design Manual is out of date. The flapjack team is reworking type spacing via Capital Framework, which is in process. They can add their updates to this issue so we can check that we all agree on spacing. We should also add standards for space after body copy (Capital Framework is currently leaning towards 30 px of spacing after each paragraph). This graphic in the Design Manual should be updated once they finish.

![screen shot 2015-01-22 at 3 07 30 pm](https://cloud.githubusercontent.com/assets/6223901/5863597/b04c3dae-a248-11e4-9ebe-4e48af086ad5.png)

@himedlooff @duelj @nataliafitzgerald @Scotchester

**Comment by Dnpizarro** [comment]
@duelj will take on this task for the March Sprint. Reference #258.

**Comment by Dnpizarro** [comment]
@duelj checking in to see if you have any updates.

**Comment by duelj** [comment]
In flapjack we have been looking at using slightly different spacing than the example above. The main differences are as follows:

• Reducing spacing intervals to 15,30, and 60 pixels
• Display, H1, H2, and H3 use 30px between heading and paragraph text
• H4, H5, and H6 use 15px between heading and paragraph text
• 30px of space between paragraphs of the same section
• 60px of space between difference sections (perhaps only 30px should be used if the new sections is a subsection of the first)

| With markers | without markers |
| --- | --- |
| ![fj_heading_spacing](https://cloud.githubusercontent.com/assets/6873734/6672421/d291efbc-cbe2-11e4-9d17-39424aaa3874.png) | ![fj_heading_spacing_a](https://cloud.githubusercontent.com/assets/6873734/6672450/01fe2270-cbe3-11e4-9d2f-4ce7e5c39390.png) |

As part of our efforts to allow for more white space on cf.gov and create a visual rhythm FJ has adopted a sort of small, medium, large approach to space between content. The intervals that we have been using so far are sm=15px, md=30px, and lg=60px. I believe most of the differences in various projects type layout stem from this approach we have taken.

**Comment by stephanieosan** [comment]
We've been using this on Owning a Home and have found it to work well overall. 

I want to call a little more attention to the issue of spacing between subsections. I do think we need a smaller amount of space between subsections than the global 60px. I second Justin's suggestion of 30 instead of 60px between subsections. Here's an example from what we're currently working on that I think shows why it's important to have different amounts of space between subsections and subsequent sections:

**All 60px, harder to tell the distinction between the two sections**
![screen shot 2015-03-17 at 4 09 33 pm](https://cloud.githubusercontent.com/assets/6433178/6696608/ec395598-ccc0-11e4-9a72-ef4eae48ef4c.png)

**60 between the two sections, 30 between each section's subsection**
![screen shot 2015-03-17 at 4 09 19 pm](https://cloud.githubusercontent.com/assets/6433178/6696624/175e058e-ccc1-11e4-9a4f-2f862af04409.png)

Where the 30px between subsection rule starts to break down, though, is when you're using a series of H1-H3s within a section. (Since those headers all have 30px below, the flow starts to feel too tight and the relationship between the header and the paragraph below becomes less clear.)
![screen shot 2015-03-17 at 4 26 09 pm](https://cloud.githubusercontent.com/assets/6433178/6696835/94f69a5a-ccc2-11e4-9a23-6e1987af642a.png)

So, maybe the 30px between subsections is only for H4-H6? And for the less likely case that you have a bunch of H1s-H3s to group into subsections, it stays at 60px, like so?
![screen shot 2015-03-17 at 4 27 08 pm](https://cloud.githubusercontent.com/assets/6433178/6696856/b545b052-ccc2-11e4-8d6a-efe69dc1b1d7.png)

**Comment by duelj** [comment]
@stephanieosan — you hit the gold mine, I really like the sound of the proposal you made for the subsection spacing. H1-H3 gets 60px and H4-H6 gets 30px. I like the look, it feels open while well grouped and keeps the intervals which is pretty great. Anyone else have thoughts on this?

**Comment by stephanieosan** [comment]
:+1: :boom:

**Comment by mebates** [comment]
Hey guys - one last thing to consider is space after paragraphs. I would try any of the above examples with having 2-3 paragraphs of text under your headers. We need to keep an eye on how that space relationship affects the headers.

**Comment by stephanieosan** [comment]
Good point, I'll take a look at that and post examples.

**Comment by stephanieosan** [comment]
Hmmm, the space after paragraphs can be tricky, because at 30 px, it's more than the space between h4-6 and the paragraphs that follow. 

| 60px between headers | 30px between headers |
| --- | --- |
| ![screen shot 2015-03-19 at 4 36 57 pm](https://cloud.githubusercontent.com/assets/6433178/6740481/830e7b06-ce56-11e4-89fd-eba4c08001b4.png) | ![screen shot 2015-03-19 at 4 37 21 pm](https://cloud.githubusercontent.com/assets/6433178/6740497/a5c5c80c-ce56-11e4-852a-99bf17a99e98.png) |

**Comment by duelj** [comment]
Your example above is a tricky case because the left column headings are a unique case to a standard text layout. They are a smaller heading size that the corresponding sub-headings (while not being a slug style) and their placement is not a standard format. I think for these reason you could argue either way on the H4 headings being sub-sections, so either spacing could be legit. I like the grouping that the 60px creates in your example but would be on board with either one. I think the headings stand out enough that the smaller spacing still works too. 

Below is a mar standard format of the same issue you raised above. This way we can see how and H3 heading with h4 sub-sections work in both spacings. 

| 60px between headers | 30px between headers |
| --- | --- |
| ![screen shot 2015-03-20 at 1 49 33 pm](https://cloud.githubusercontent.com/assets/6873734/6757652/164aac98-cf09-11e4-8541-a54d3cc6fc65.png) | ![screen shot 2015-03-20 at 1 49 18 pm](https://cloud.githubusercontent.com/assets/6873734/6757659/1e15d68c-cf09-11e4-8de9-3132c51f4ab2.png) |

**Comment by stephanieosan** [comment]
Those are good examples. I think it also depends on the relationships in the content. The 30 px example shows a clearer relationship hierarchy (the h4s are under and related to that h3, the subsequent h3 represents a new section). But, maybe there are cases where you wouldn't want such a strong relationship, and the h4s don't actually "belong" to that h3?

We could leave it up to the designer? 30 or 60 px, depending on how the content is structured?

**Comment by duelj** [comment]
+1

**Comment by stephanieosan** [comment]
Yay! Going once...going twice...

**Comment by nataliafitzgerald** [comment]
@stephanieosan / @duelj 
For the spacing after headers (before paragraph text) most of the spacing is looking good. The only one that feels like a bit too much space is the space after Header 3. But, I imagine 15 px would be too little. So, are we choosing to sacrifice this one for the sake of our 15/30/60 spacing rule? 

In the last example that @stephanieosan posted, I support leaving it to the designer unless we find something that we can define as a rule. In the 30 px between headers example, the H4 sections do feel pretty nested into the H3 (so I agree with the comment about this working if they were closely associated/children of the H4 section). Do we have any instances like this further up the hierarchy, like multiple H3 sections under a H2?

**Comment by duelj** [comment]
##### Part 1 – spacing intervals and H3 issue

I would vote for keeping the 15/30/60 as it is easy to use, remember, and is currently in a lot of the Capital Framework spacing (I believe). I think it could also be said we are sacrificing the rhythm created by those spacing intervals if we make the H3 a bespoke spacing (20px for example). 

I do think that there are going to be fringe cases where the spacing intervals might not feel spot on, but if we adjust for those instances it will create extra code, inconsistency, and complexity that could be avoided by being at ease with slightly generous spacing in some instances. 

##### Part 2 – Nested headers and designer discretion

Partially to this point FJ has tried to pair headers together that are two levels apart (ex: intro sections have H1 titles and H3 subtext with body copy below). This would in theory go all the way down the hierarchy as well, H2/H4, H3/H5, and H4/H6. However, in our work so far we rarely use nested headers below the H2/H4 level. This is something that OAH has more experience with and can speak to whether would work in their situation. But it is something to keep in mind as it would help the spacing issue @nataliafitzgerald raised. 

I think we could probably find cases for less/additional spacing between all nested headers if we tried different variations, but I think what we have discussed above is a good foundation to build from as we get more things "in the wild." If we see more resolute examples of where nested headers aren't working down the road we can reassess with a more defined sample.

**Comment by nataliafitzgerald** [comment]
@duelj - I agree that this is a good foundation to build from. And, the sacrifice for the spacing between H3 and paragraph text seems worth it for keeping with the 15/30/60 rule.

**Comment by duelj** [comment]
It sounds like we are in a good place on wrapping this issue up, and as we move forward we will keep an eye on how these spacing guidelines are working out? Perhaps when I close this issue, we can make an open-ended new one that people can post examples of issues they are having with this set up as we work with it more? Then we have one location to document problems and can address it at a later date if we see there becomes a growing list?

**Comment by mebates** [comment]
Steps to close out this issue: 
- [ ] Update description and image in the Design Manual
- [ ] Update spacing built into Capital Framework
- [ ] Update .ai template(s) to reflect new standards

Do we have/need/want a point person for each of these steps?

**Comment by Dnpizarro** [comment]
Thanks @mebates for clarifying the next steps. 

Since @duelj worked on this issue, the task of updating the .ai would fall on his plate. As far as the other two tasks, since they are a fewd updates we would need to assign a fewd to them. @duelj do you think you can provide an updated description and image for the Design Manual? Once we have these assets, we can pass them along to a fewd to update.

**Comment by stephanieosan** [comment]
I'm happy to help out on bringing this to the finish line, either by writing the description or by updating the ai template.

**Comment by duelj** [comment]
I will be sure to update the design, write the description and will post that content here when I have something to show.

**Comment by duelj** [comment]
This is my first stab at laying out the information covered in this issue within the design manual layout. I could use some feedback and thoughts on how those with my experience might suggest formatting this for the DM. My first impression is given its added complexity, it might be best to make it a new section for spacing, but was unsure how to tie this in the the web type if done, perhaps it could be titled "web type spacing." In the example below I tried to continue the hierarchy that exists now in the design manual with the added content. I have also tried to write some description for the sections as well which could also use feedback. 

![dm_type_spacing_v1a](https://cloud.githubusercontent.com/assets/6873734/6905670/a79116a6-d6f7-11e4-90ec-2d7080543d5d.png)

**Comment by mebates** [comment]
Hey @duelj - I think this is very clear. I think it's fine to still live under 'Web typesetting', as long as we can easily add in those tertiary headers you have ('header and body copy'). The page will be getting very long, but I think we can address that and the general content strategy/info architecture in another issue if we feel the need to.

**Comment by stephanieosan** [comment]
:+1:

**Comment by duelj** [comment]
I will work on updating the design template to reflect these changes in the paragraph styles, then we can look at what the next steps are in approving this and getting it into the design manual in the format above. Thanks for the input.

**Comment by Dnpizarro** [comment]
Thanks for pushing this through @duelj ! Moving this to the April sprint.

**Comment by mebates** [comment]
Pulling this into July so we can get this updated across our standards:
- [ ] Add to the Design Manual
- [ ] Update Capital Framework
- [x] Update .ai template(s) to reflect new standard

**Comment by ascott1** [comment]
Hey all, one thing of note from a FEWD perspective. The way we are calculating spacing does not take into account the line-height of a the text in CSS. In reality the spacing starts below the line-height, making those fixed values really hard to account for.

For example, check out this developer tool's screenshot of a heading from OaH:

![screen shot 2015-08-14 at 2 55 13 pm](https://cloud.githubusercontent.com/assets/212533/9281660/9d011070-4294-11e5-99ce-dd7906f3fd0e.png)

You can see that the margin below the text (highlighted in orange) begins where the line height ends. Where this is a unique challenge is in that that line-height spacing is relative to the size of the text.

Just wanted to make sure you're all aware of these potential challenges. How can we make sure that these standards work well with adaptive web designs? Or are minor discrepancies (to the tune of a couple of pixels) on the web something we're comfortable with?

**Comment by duelj** [comment]
@ascott1 That sounds tricky. If I documented the spaces based off the descender height vs. the baseline it seems like that would help. If that example you showed had no descender would the spacing still be calculated from the same spot? Also, in FJ our heading patterns jump one size down for smaller screens, is the padding you are showing in orange specific to the h1? So, if the h1 changed to h2 would the orange spacing change?

**Comment by ascott1** [comment]
@duelj it appears that the height remains the same without the descender:

![screen shot 2015-08-19 at 4 16 04 pm](https://cloud.githubusercontent.com/assets/212533/9367796/aa6080aa-468d-11e5-93eb-04c81d5782e0.png)

![screen shot 2015-08-19 at 4 16 58 pm](https://cloud.githubusercontent.com/assets/212533/9367814/c41bbc8a-468d-11e5-9bdc-a999333695c2.png)

The orange margin is based on whatever we have defined with a pixel value, while the blue highlight is the line height, which is relative to the font-size. As you can see in the second example, this has an effect on top margins/padding as well.

**Comment by ascott1** [comment]
This is an issue with all type on the web, so paragpraphs etc. have the same challenges:

![screen shot 2015-08-19 at 4 19 56 pm](https://cloud.githubusercontent.com/assets/212533/9367897/341cfe40-468e-11e5-824b-1f6284aa7790.png)

This means if we have an h1 with a 30px bottom margin followed by a paragraph, the space between those two elements is actually more than 30px.

**Comment by nataliafitzgerald** [comment]
@jjames - In working on web projects I have noticed a few potential problem areas with regard to the spacing between type elements in the standards we have set. Some of these issues exist in our attempts to stay within the multiples of 15 rule. 

##### H3 Spacing

The 30px space after H3 feels too large. I flagged this originally in this issue but let it go in order to maintain the multiples of 15 approach (the alternative proposal was 20 px). But, after reading @ascott1's posts and looking at your original mock-ups, the spacing I see the spacing was shown from the baseline of H3 to the top of the ascender of the paragraph text. So, it looks substantially closer than it would coded out. 

This is what we have now (30px between H3 and paragraph and 30px between paragraphs): 
<img width="630" alt="screen shot 2015-09-01 at 5 28 44 pm" src="https://cloud.githubusercontent.com/assets/6887128/9617146/f4207920-50ce-11e5-93bf-bf02fbed26af.png">

This is how 15 px would potentially look.
<img width="601" alt="screen shot 2015-09-01 at 5 14 27 pm" src="https://cloud.githubusercontent.com/assets/6887128/9616646/5c34dcc4-50cd-11e5-8132-bf27f3acb956.png">

This is how 20px after H2 and 15px between paragraphs would look (this approach feels like the best fit, but we'd have to see it in code to know for sure): 
<img width="610" alt="screen shot 2015-09-01 at 5 37 01 pm" src="https://cloud.githubusercontent.com/assets/6887128/9617497/218c97c6-50d0-11e5-81b9-5674719f967d.png">

#### H4 spacing

Also, with the space between H4 and paragraph text set to 15 px and the space between paragraphs set to 30 px, the visual connection between the header and the paragraphs starts to fall apart. The H4 holds on to that first paragraph but the subsequent paragraphs look like they are floating without a header. 

This is what we have now 15px after H4 and 30 px between paragraphs: 
<img width="647" alt="screen shot 2015-09-01 at 4 54 04 pm" src="https://cloud.githubusercontent.com/assets/6887128/9617196/540df646-50cf-11e5-8d6f-d64466019622.png">

This is how 15px after H4 and 15 px between paragraphs: 
<img width="667" alt="screen shot 2015-09-01 at 4 45 14 pm" src="https://cloud.githubusercontent.com/assets/6887128/9617217/6d3d1a48-50cf-11e5-8b5f-e9d0fff8a773.png">

And here's how 20px after H4 and 15px between paragraphs would look (this approach feels like the best fit, but we'd have to see it in code to know for sure):
<img width="670" alt="screen shot 2015-09-01 at 4 48 47 pm" src="https://cloud.githubusercontent.com/assets/6887128/9617238/853744e8-50cf-11e5-9a45-46203f8c7029.png">

@duelj - Would it be possible to code out the hierarchy that you proposed above so that we can see it in practice and address any areas of concern? This isn't an urgent matter but I would like to move in the direction of taking another look at our hierarchy and spacing and make the adjustments that are needed. I know that there are a lot of variables that go into creating this spacing and that it is a truly delicate balance. You've done a great job at navigating this and setting up a hierarchy that can work for a wide variety of use cases.

**Comment by nataliafitzgerald** [comment]
#### Spacing between H2 and paragraph and H3 and paragraph

@danny8000 and I are working on building the KBYO landing page. I went ahead and tested out  some of the spacing issues I flagged in my previous post so as to get an in-browser comparison. 

##### Here's what I found

30 px spacing after H2 and H3 (the current approved update to the Design Manual/Capital Framework) feels way too generous. 15 px spacing after H2 and H3 feels a lot more natural and visually pleasing. I would still like to test this out in other combinations (such as 2 paragraphs after H2 and H3) but, in looking through a lot of our recent web work I have mentally flagged this issue (particularly with the space between H3 and paragraph). 

##### Moving forward

I would also like us to start to more clearly define the space between headers, for example H1/H2, H3/H4, H1/H3, H2/H4 and so on. Perhaps a lot of this is already defined but, if not, it makes sense for us to add some standards for common combinations that come up. If it is defined I'd like to review it coded out.   

There's also the question of leading/line spacing. This may be best tested out in code. We should add this detail to the Design Manual. Ideally it would be best to see the proposed solution coded out. If this is already worked into Capital Framework I would like to make sure that our web design template reflects how our spacing will look when coded.

| 30px (after H2 and H3) | 15px (after H2 and H3) |
| --- | --- |
| ![30px-space-after-headers-1](https://cloud.githubusercontent.com/assets/6887128/9672735/1e40f96c-526b-11e5-9500-17df83f9ece6.png) | ![15px-space-after-headers-2](https://cloud.githubusercontent.com/assets/6887128/9672741/2b1e2df8-526b-11e5-805e-0cf977d30993.png) |

Here's the same image with measurements included: 

| 30px (after H2 and H3) | 15px (after H2 and H3) |
| --- | --- |
| ![30px-space-after-headers-1](https://cloud.githubusercontent.com/assets/6887128/9672922/eb38e44c-526c-11e5-92ca-e4fe2281f80e.png) | ![15px-space-after-headers-1](https://cloud.githubusercontent.com/assets/6887128/9672928/f44b76da-526c-11e5-9522-59f20d2fa363.png) |

@Scotchester @ajbush @duelj

**Comment by KimberlyMunoz** [comment]
On the spacing/descender issue, it looks like we're eyeballing the spacing changes in Capital Framework. 

```
h1,
.h1 {
    @font-size: 34px;
    @line-height: 44px;

    margin-top: 0;
    // Spacing in the design manual is based off of the baseline so this margin
    // number has been eyeballed to be 30px.
    margin-bottom: unit( 16px / @font-size, em );
    font-size: unit( @font-size / @base-font-size-px, em );
    line-height: unit( @line-height / @font-size );

    .respond-to-max(@mobile-max, {
        .h2();
    });
}
```

**Comment by duelj** [comment]
@nataliafitzgerald and @ascott1 - just want to make sure we are all on the same page here. 

#### Summary of issue (want to make sure I am understanding)

As @KimberlyMunoz pointed out Capital Framework already uses bottom margins that "eyeball" the overall spacing design has specified between a given header and the text that follows it. It seems the [original comment by Adam](https://github.com/cfpb/design-manual/issues/269#issuecomment-131213101) was making us aware that these margins are "eyeballed" and that to get the spacing intervals we want (15,30, 60px) the actual margins coded will be estimated to account for the container the text is in (which is the whole descender issue). I didn't fully understand how this was being accomplished in code and my follow up to Adam was to make sure that the size change for the header at mobile was also adjusting the margins for that header size change. I have been reassured that it is, and it is documented in Capital Framework as well. 

#### Proposed solution

The examples shared by Natalia show the importance of the "eyeballing" work done by the FEWDs on Capital Framework. My impression is that those examples shared from Your Have the Right do not use the Capital Framework type spacing (with the adjusted bottom margins) **Is this correct?** If so, I think before any discussion around adjusting header spacing on a DM issue that has already had approval (just waiting to be published) those examples should be tested using the Capital Framework adjusted margins to see if the same spacing concerns still exist.

**Comment by duelj** [comment]
To try and share a visual of how this works out with the code that Kimberly shared above an H1 uses a 16px margin to "eyeball" the look of an overall 30px spacing interval from the baseline to ascender of the next text section. This example can be seen in code for the page title of the [About Us page](http://beta.consumerfinance.gov/about-us/)

![screen shot 2015-09-09 at 1 28 57 pm](https://cloud.githubusercontent.com/assets/6873734/9769252/fd8a6844-56f6-11e5-8a17-93873564aac8.png)

**Comment by Scotchester** [comment]
The "eyeballing" approach (not a great name for it, but I think we're all on the same page) does indeed work well in these predictable cases like the space after a heading.

The problem with this approach is when it's unpredictable. For example, consider a scenario where you need to set the top margin on some kind of block of content. The first bit of text in that block could be anything from an H1 to H6. and thus the amount you have to compensate for the line height of that first bit of text is unpredictable.

Ultimately, there's no perfect way around the issues inherent with line-height. As you can see from the great example Justin just posted, it's hard to even approximate how much extra space will be above and below the text at different sizes. (6 above, 9 below the H1, but 6 and 6 on the H3).

To an extent, we're going to have to set the rules as best we can for the most common scenarios, and live with a margin of error of something like ±5px in all other scenarios.

All that to say, if it makes more sense to display the guidelines on the Design Manual page with the baseline-to-ascender values, I think that's fine. We can keep on keepin' on with the manual adjustments (where possible) within the CSS.

**Comment by ajbush** [comment]
We talked about this issue yesterday in small group working session.

Those who were present seemed to agree with what @Scotchester mentioned:

> The problem with this approach is when it's unpredictable...Ultimately, there's no perfect way around the issues inherent with line-height. As you can see from the great example Justin just posted, it's hard to even approximate how much extra space will be above and below the text at different sizes. (6 above, 9 below the H1, but 6 and 6 on the H3).

The group also kinda wondered if there was a better or alternative way to go about making our design templates match up better with what's in production.

We also discussed @nataliafitzgerald's [suggestion for spacing adjustments](https://github.com/cfpb/design-manual/issues/269#issuecomment-137598822) and it seems like something that she thinks needs to be tested and explored more first before we make the switch. I think for now we are cool with sticking with the current intervals that were approved [here](https://github.com/cfpb/design-manual/issues/269#issuecomment-87812022) for the v1 release and we'll watch this issue for developments.

**Comment by nataliafitzgerald** [comment]
@jimmynotjim @duelj 

After reviewing and testing with @Scotchester in both code and illustrator we have found that the following appear to work as a rule of thumb:
- Display, H1, H2, H3, H4, H5, H6 use 15px bottom margin when followed by paragraph text (Avenir Next or Georgia)
- 15px of space between paragraphs of the same section
- 30px of space between headings (for example - see "Creating new mortgage disclosures" http://www.consumerfinance.gov/know-before-you-owe/)

Note: This is based on actual margin-bottom measurements in CSS (not baseline to cap height). This seems to work consistently with the space after (within paragraph style) in illustrator.

We tested this in a variety of combinations but welcome any examples where this may not work.

**Comment by duelj** [comment]
#### Update from 10/22/15 working meeting with @Scotchester, @nataliafitzgerald, @doguin, @jimmynotjim, and myself.
- Changes were made to all header and paragraph spacing measurements to better reflect how they were being measured in code. The measurements _for coding_ are as follows:
  - Heading to paragraph: H1-3 = 45px above & 20px below. H4-6 = 30px above, 15px below
  - Heading & heading: 30px (all)
  - Between paragraphs: 20px
  - Between sections of flowing content: dictated by heading above spacing
- Spacing between modules (v1 molecules & organisms) is still defined by the 60px after spacing.
- When rule line is used spacing should be 60px after section – rule line – 30px above header of next section.
- Because of the way we are determining spacing for code now line height would impact the spacing so we made decisions on header leading discussion #349 as well. Details of adjustments can be found on that issue.

##### Next steps:
- Justin to create DM page layout, post here for approval 
- Determine need for support on updating .ai template file when update DM page is posted. 
- Build the paragraph styles off of the coding.

**Comment by duelj** [comment]
I tried showing the spacing intervals between headings and paragraph copy but the way the spacing is now being measured makes it hard to visualize like we had before, the more general labeling approach seemed to communicate the ideas more clearly. 
@nataliafitzgerald and @benguhin -- could you please review the layout and description copy to see if it is ready for approval. 

#### Proposed update to DM web type spacing section

![dm_type_spacing_v1](https://cloud.githubusercontent.com/assets/6873734/10770824/b795124c-7cc3-11e5-82e4-a7567d2b35c7.png)

##### Example of how trying to label spacing would look

![screen shot 2015-10-27 at 4 00 14 pm](https://cloud.githubusercontent.com/assets/6873734/10770852/dc8d4eca-7cc3-11e5-9eb6-d4cf03df74cf.png)

**Comment by jimmynotjim** [comment]
PR for Capital Framework side of things here https://github.com/cfpb/cf-core/pull/53

**Comment by duelj** [comment]
#### Working session feedback
- specific spacing label is helpful but style could be adjusted to be less complex
- Add in description copy to explain how spacing is measured so that the minor space difference have better context.

#### Updated proposal for DM page

![dm_type_spacing_v1](https://cloud.githubusercontent.com/assets/6873734/10773047/94960ccc-7ccf-11e5-909b-59bd98f69a9e.png)

**Comment by ohsk** [comment]
Looks clean, Justin! :+1:

**Comment by Scotchester** [comment]
@duelj I like the new block format, but the green on grey is a little hard to read.

**Comment by benguhin** [comment]
Looks great :+1:

**Comment by nataliafitzgerald** [comment]
In order to start moving in the direction of bringing the Typography page up to date and finding a proper location for this new content (and additional content that will be coming soon), some reorganizing and restructuring was needed. I also noticed a number of things (within the current page) that are either incorrect and/or confusing. 

I have put together a GoogleDoc to work through updating the content on the page. If there are any designers or UX'ers that want to chime in, the page is located here: https://docs.google.com/document/d/19B6l_9EA8MlU-pikOB3GccoO2VzWlZk7_2cqqI1p99k/edit#. 

In the interest in getting these standards documented, we are moving forward with this update quickly, so we won't be able to address everything in our first push. I will post an issue for the additional things that we will tackle in a subsequent push. 

@benguhin @Dnpizarro

**Comment by nataliafitzgerald** [comment]
In the interest of getting this particular issue closed out @Scotchester and I will work on first pushing the update to the "Web typesetting" section. That final content can be found here: https://docs.google.com/a/cfpb.gov/document/d/17-6Ij_-mGM0x0Gle_fAFkPzT1EOhX4OiZZpEXqUa3N0/edit?usp=sharing

**Comment by nataliafitzgerald** [comment]
Here's the updated mock-up for the Design Manual section on spacing. I used our brand green for labeling the measurements in order to remain consistent with the current Design Manual styling. As part of our upcoming DM content update (which I am thinking will have some design updates as well), we should discuss changing our labeling color throughout the guide in order to provide sufficient text contrast and comply with our own standards. 
![dm_type_spacing_v3](https://cloud.githubusercontent.com/assets/6887128/10898452/8b3f86da-8198-11e5-8225-cab94372b4b3.png)

@Scotchester

**Comment by duelj** [comment]
This looks great to me, the only thing I can see is shifting the body copy example to match the margins of the header examples above so that the measurement label is left in a sort of 'hanging' position. 
<img width="316" alt="screen shot 2015-11-03 at 11 14 20 am" src="https://cloud.githubusercontent.com/assets/6873734/10913479/1270bfba-821c-11e5-9be6-3468ae4d2c66.png">

**Comment by nataliafitzgerald** [comment]
@duelj - Sure, I'll make that update. I've made some other little tweaks so I'll repost.

**Comment by Scotchester** [comment]
We have a demo page showing this spacing in a number of combinations! http://cfpb.github.io/cf-type-testing/dist/

Well, actually, what the demo page is showing is actually a slightly modified proposal that @nataliafitzgerald and I developed yesterday...

In looking carefully at the examples on the page, we found that the proposed rule for reduced margin between two adjacent headings caused a problem in running copy.

In an example such as this:

```
h2
h3
p
p
h3
p
```

With the current proposal, the space between the h2 and h3 is only 30px, but the space between the p and the second h3 is 45px. The second h3 looks detached from the stuff above it, even though it's part of the same level of hierarchy as the first h3.

Natalia and I came to the conclusion that the best way to solve this problem is to let go of having perfectly multiplied spacing intervals and just use a sliding scale for the margins above headings. This will ensure that the spacing always reinforces the document hierarchy, and never muddles it.

(As an aside, the FJ content team says that headings should not be used together; it’s a big no no for them. There should always be text to introduce the concept before the first child heading. So, another reason not to make a rule for headers stacked together.)

Here're our proposed values:
- H1: 60px above (though it never follows other text, in practice)
- H2: 45px above
- H3: 35px above
- H4: 25px above
- H5: 20px above
- H6: 20px above (sticking at 20 here, because going to 15 would make it even with the space below it)

Now, the spacing above the new Lead Paragraph style (proposed for usage instead of H3 in heroes and page intro modules) would use whatever value most closely matches [the current Hero spec](http://nataliafitzgerald.github.io/design-manual/ui-toolkit/heroes.html#desktop), which currently specifies 30px as a baseline-to-cap-height value. That's about the only common situation in which two heading-like styles should be used together.

Once again, please [check out the demo](http://cfpb.github.io/cf-type-testing/dist/) of this proposed update and let us know if you find any issues or would like to see other examples.

**Comment by Scotchester** [comment]
P.S.: As with the list issue, we'd like the following people specifically to give it a look: @duelj @ajbush @jimmynotjim, but comments and concerns are welcome from all.

**Comment by stephanieosan** [comment]
So, how does this affect our methodology for spacing between elements in general? Will we still be using 15/30/60 when we space other elements on the page, or are we throwing that framework out entirely now?

**Comment by Scotchester** [comment]
Great question!

Our proposal really only affects adjacent headings and paragraphs in in running text, so general spacing between elements would still use the multiples of 15 system.

**Comment by duelj** [comment]
Spent some time looking at the demo and playing with different heading levels in there, I don't have any concerns, visually it looks nice. 

My only critique is I wish we were able to maintain a more memorable system to the spacing. Between code and paragraph styles this likely will not create an issue, but it felt easier to spot mistakes when I could reference a simple system in my head, I don't know that I would trust myself to remember the current proposal as readily. Apart from that looks like you all have done a lot of testing and trust that it is all well thought out. Look forward to having it wrapped up!

**Comment by nataliafitzgerald** [comment]
Yeah, I know what you mean @duelj. We definitely tried to stay true to the more memorable spacing system but in looking at how this played out visually across many combinations there were a number of instances where the visual/type layout was suffering in order to stay locked into this system. As @Scotchester mentioned, this will only affect header spacing which will be defined in our paragraph styles within illustrator and our code on our website. For spacing between elements, the multiples of 15 system will still be in place. Thanks for testing it out on your end!

**Comment by jimmynotjim** [comment]
Looks good and it makes sense to me. As long as everyone sticks to the values set in Ai and the CSS, we shouldn't need to worry about the values all that much and can trust they are correct when displayed.

**Comment by nataliafitzgerald** [comment]
Updated code sample: 
http://cfpb.github.io/cf-type-testing/dist/

Updated layout document: 
![dm_type_spacing_v8-01](https://cloud.githubusercontent.com/assets/6887128/11223414/c80d64aa-8d3d-11e5-8f19-640190fa0600.png)

**Comment by Scotchester** [comment]
@duelj Good news! We've changed our position again and everything is a multiple of 15 again :)

H1: 60px above/15px below
H2: 45px above/15px below
H3: 30px above/15px below
H4: 30px above/15px below
H5: 30px above/15px below
H6: 30px above/15px below

Now reflected on the [demo page](http://cfpb.github.io/cf-type-testing/dist/).

**Comment by designlanguage** [comment]
@nataliafitzgerald - The spacing looks great, but I have some comments on documentation. 
- I would call the second category "Body copy followed by heading." The way you have it now looks almost identical to the preceding category.
- The heading/body copy examples should be identical in the first and second categories (only the green callouts would be different). That includes showing Display in the second category and making the spaces between body copy and heading accurate in the first category. Currently they don't match up.
- I understand that using two columns saves vertical space, but it's not ideal because you don't see text before Heading 4 to visualize the amount of space allowed. It's also a little hard to look at since nothing is aligned between columns. Could this be done in one column?
- Since this is about spacing and not the heading styles, maybe we can keep this to a single column and eliminate a bunch of the redundant examples. In the first category, only the space between display and body is different. In the second, only between body copy and Heading 2. For example, the heading could read something like "Heading 2 and below"?
- In the same spirit as the above comment, I think we only need one example of the spacing between paragraphs of body text. There is no difference in spacing between serif or sans paragraphs.
- If this layout remains as is, nudge Heading 2 in to match the other entries in the first section.

**Comment by nataliafitzgerald** [comment]
@designlanguage - Based on your proposed change to the header, how would you rewrite the content below "Heading following body copy"?

**Comment by caheberer** [comment]
:+1: to the proposed spacing! Nice work to all involved.

**Comment by Dnpizarro** [comment]
The spacing recommendations are working nicely throughout. Great job everyone!

**Comment by designlanguage** [comment]
@nataliafitzgerald - It seems like the description would still apply. The heading in the example could say "Headings 3-6" if that makes more sense.

**Comment by duelj** [comment]
Either option posted this week works for me, I think we should try to move forward with where we are at even if it doesn't feel perfect. We for sure are more than 80% of the way there and need to get this in the DM as soon as possible. 

A lot of great thought and work has went into this, and the latest demo looks like it is working well to me.

**Comment by jimmynotjim** [comment]
Looks good from here. @Scotchester is going to send a PR to my open PR with the adjustments and then we should be able to close this out.

**Comment by nataliafitzgerald** [comment]
Here is the update to the layout (thanks to @designlanguage for his feedback!)
![dm_type_spacing_v9-01](https://cloud.githubusercontent.com/assets/6887128/11228280/88c0279e-8d59-11e5-9c66-1171d3eefbe2.png)

**Comment by jenn-franklin** [comment]
:+1: to 30px after display and 15px after all other headers. This looks great!

**Comment by jimmynotjim** [comment]
Stamped final and merged into Capital Framework cf-core. Update your projects to include the changes.
