### ISSUE TITLE
Logo updates: Tracking what needs to be done

### ISSUE THREAD

**Issue by klocraft** [cfpb/design-manual#330]
<h2>Tracking updates to the CFPB logo. </h2>

Please add to this list if you see anything is missing, and make notes if you are working on any portion of  below.
- [ ] **Update asset library**
  <br>
  This will include reorganizing logos by category, rather than color. (Ex: Primary logo, Vertical logo, Isolated logo). Assigned to @klocraft.
  <br>
  <br>
- [ ] **Update Design Manual**
  <br>
  This will include confirming size standards and removing the old "Horizontal logo." New images are required. 
  <br>
  <br>
- [ ] **Update the Design Toolkit on the Intranet** <br>
  This will include confirming what file types should be available for download.
  <br>
  <br>
- [ ] **Updating cf.gov downloads** 
  <br>
  <br>
- [ ] **Updating all Illustrator, InDesign, and Microsoft templates**<br>
  InDesign templates assigned to @klocraft and @Dnpizarro<br>
  Microsoft templates assigned to @elizbond 
  <br>
  <br>
- [ ] **Communicate changes to Bureau** <br>
  This will include articles in weekly newsletters.
  <br>
  <br>
- [ ] **Other?**

**Comment by Dnpizarro** [comment]
@klocraft I'm adding this to the August Sprint.

**Comment by caheberer** [comment]
Asking @elizbond for status

**Comment by caheberer** [comment]
Move to Graphic Design Repo.
