### ISSUE TITLE
Reduce bottom padding for wells

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#463]
### Description
The current bottom padding in wells is set to 60px. This creates a great deal of empty space and an imbalance within the well. 
<img width="1328" alt="screen shot 2017-03-09 at 5 34 48 pm" src="https://cloud.githubusercontent.com/assets/6887128/23775096/ee2a33a4-04f4-11e7-88e7-4e6cd10caca4.png">

### Task
Reduce the bottom padding in wells to 30px. This will create balance within the well and on the page. 
<img width="1298" alt="screen shot 2017-03-09 at 5 34 20 pm" src="https://cloud.githubusercontent.com/assets/6887128/23775147/28dd5012-04f5-11e7-86d2-47441405cae7.png">

#### Ready Checklist
- [X] Has acceptance criteria or is part of a user story
- [X] Describes the smallest possible chunk of work
- [X] There are no blockers to starting the task
- [  ] All information necessary for completion is available 
      - All input from other disciplines (Design/Ux/Content/FEWD/BEWD) is attached
      - There are no outstanding questions for stakeholders

#### Acceptance criteria
- [  ] Discussion within the team 
- [  ] Supporting DM images are created
- [  ] Design Manual [wells page](https://cfpb.github.io/design-manual/page-components/wells.html) is updated 

#### Done Checklist
- [ ] All work has been peer-reviewed
- [ ] Has been acceptance tested and meets acceptance criteria
- [ ] All code or assets are merged to master
- [ ] Documentation has been updated.

**Comment by nataliafitzgerald** [comment]
@ajbush @huetingj @caheberer @marteki @Dnpizarro 
Looking for some discussion regarding this recommendation. Are you in support of this change? Please note that this is only one of a few recommendations I am making regarding the well. But, it's a small step in the right direction.

**Comment by marteki** [comment]
Yes, I'm in support of this change. It was confusing to see the 60px implementation on previous projects, and I feel like 30px is the right choice for bottom padding on all the instances I've come across to date.

**Comment by jenn-franklin** [comment]
I support this change. Particularly feels like too much space as it is now on small screens.

**Comment by Scotchester** [comment]
:+1:

**Comment by ajbush** [comment]
:+1:

**Comment by caheberer** [comment]
👍

**Comment by nataliafitzgerald** [comment]
@jimmynotjim @Scotchester 
It looks like there is general consensus about this update. How do we go about making it happen?

**Comment by jimmynotjim** [comment]
Moved to the [Capital Framework issue tracker](https://github.com/cfpb/capital-framework/issues/638)

**Comment by jimmynotjim** [comment]
Done in https://github.com/cfpb/capital-framework/pull/687
