### ISSUE TITLE
Add well organism to Capital Framework

### ISSUE THREAD

**Issue by nataliafitzgerald** [cfpb/design-manual#470]
### User story  

As a Designer/Developer, I want the well organism (o-well) to be included in Capital Framework so that I can feel confident that o-well modifiers (o-well-featured, o-well-notification) pull from a consistent base design. 

#### Acceptance criteria
- [ ] Related tasks are completed
- [ ] Documentation is updated to reflect additions and adjustments

#### Related tasks:
- [x] Remove -30px right and left margin for wells [#469](https://github.com/cfpb/design-manual/issues/469)
- [x] Reduce bottom padding for wells (https://github.com/cfpb/design-manual/issues/463)
- [ ] Explore combining Wells, FCM, and Notification patterns #471

**Comment by jimmynotjim** [comment]
@nataliafitzgerald We did the major bits, not sure we should bother waiting on the conversation in #471 to close this. Thoughts?

**Comment by nataliafitzgerald** [comment]
Yeah I don't see the conversation in [471](https://github.com/cfpb/design-manual/issues/471) as a blocker to closing this one out.
